### ISSUE TITLE
Problems with memory on WebAssembly

### ISSUE THREAD

**Issue by paulo-coutinho** [cschreib/lxgui#103]
Hi,

I have this error when open webgl demo (1 or 2):

![image](https://user-images.githubusercontent.com/395096/152600204-ddd39eaa-a75b-4323-9f48-215784114fbc.png)

Maybe WASM demos need be compiled with `-s ALLOW_MEMORY_GROWTH=1`.

Thanks.

**Comment by cschreib** [comment]
I can confirm the issue, thank you for reporting! I believe this option is already set, however, so it must be something else. I will investigate!

**Comment by cschreib** [comment]
I found the error! Sneaky, as it does not trigger on normal DPI systems (e.g., my desktop, which I use for regular testing). Thank you again for reporting the issue.
