### ISSUE TITLE
Add SDL backend

### ISSUE THREAD

**Issue by cschreib** [cschreib/lxgui#51]
SDL is a fairly standard and widely supported rendering/input backend. Adding an SDL backend to lxgui would increase the number of projects that could use the library.

Differences with SFML:
 - SDL is written in C, so I will likely have to write more boilerplate to get it all working, unless I use something like https://github.com/libSDL2pp/libSDL2pp? But then it has to be inter-operable with pure SDL, in case users use their C API or another C++ wrapper.
 - SDL has support for WebAssembly / emscripten, which is really good for demos and getting people engaged.

**Comment by cschreib** [comment]
Work started in https://github.com/cschreib/lxgui/tree/sdl-backend

**Comment by cschreib** [comment]
Input backend is now working. Working on renderer backend now.

**Comment by cschreib-ibex** [comment]
Renderer backend almost fully working, still need to figure out these things:
 - fine tune the pre-multiplied alpha blending, which doesn't look quite right yet.
 - add ad-hoc support for rotated textures (edge textures in particular)
 - add support for simple color gradients

**Comment by cschreib** [comment]
Renderer backend almost fully working, still need to figure out these things:
 - fine tune the pre-multiplied alpha blending, which doesn't look quite right yet.
 - add ad-hoc support for rotated textures (edge textures in particular)
 - add support for simple color gradients

**Comment by cschreib** [comment]
Color gradients are now working.

**Comment by cschreib** [comment]
Rotated textures and texture repeat are now working (with a slight implementation issue in texture repeat).

**Comment by cschreib** [comment]
Pre-multiplied alpha blending is now fixed.

**Comment by cschreib** [comment]
Work merged into master.
